### ISSUE TITLE
how to use the iptables with mark.

### ISSUE THREAD

**Issue by jaywayjayway** [larsks/kube-ip-manager#4]
after creating a _VIP_ with a iptables rule 

```
  -A KUBE-PUBLIC -d 192.168.1.41/32 -p tcp -m tcp --dport 8080 -m comment --comment web -j MARK --set-mark 1
```

handling the rule,how I use it for cluster vip ?????

```
spec:
  clusterIP: 172.16.184.4   ### come from  k8s ####
  deprecatedPublicIPs:
  - 100.100.100.1
  ports:
  - nodePort: 0
    port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity
```
